# -*- coding: utf-8 -*-
"""Scrap_Judaique

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPvnKc0SoiIPpvEmZhHht35G2AJXJO0k
"""

import requests
import pandas as pd
from datetime import datetime

# URL de l'API (on garde la même base)
BASE_URL = "https://datahub.bordeaux-metropole.fr/api/records/1.0/search/"

params = {
    "dataset": "bor_frequentation_piscine_tr",
    "rows": 50,  # On récupère tout pour filtrer nous-même
    "q": ""
}

def afficher_affluence_judaique():
    print("🔄 Récupération des données corrigées...")

    try:
        response = requests.get(BASE_URL, params=params)
        data = response.json()

        if data['nhits'] > 0:
            # On récupère les champs des résultats
            records = [r['fields'] for r in data['records']]
            df = pd.DataFrame(records)

            # --- FILTRAGE POUR JUDAÏQUE ---
            # On cherche "Juda" ou "Boiteux" dans la colonne 'etablissement_etalib'
            # (Note: par sécurité, on convertit en chaîne de caractères 'str')
            resultat = df[df['etablissement_etalib'].astype(str).str.contains("Juda|Boiteux", case=False, na=False)]

            if not resultat.empty:
                # On prend la première ligne trouvée (souvent le grand bassin)
                # Il est possible qu'il y ait plusieurs zones (bassin 25m, 50m, etc.)
                # On va faire une boucle pour tout afficher si plusieurs zones existent

                print("\n🏊 RÉSULTATS POUR PISCINE JUDAÏQUE - JEAN BOITEUX :")

                for index, row in resultat.iterrows():
                    zone = row.get('fmizonlib', 'Zone inconnue') # Nom de la zone (ex: Bassin 50m)
                    actuel = row.get('fmicourante', 0)           # Affluence actuelle
                    maximum = row.get('fmizonmax', 1)            # Capacité max
                    maj = row.get('datemiseajour', 'N/A')        # Heure de mise à jour

                    # Calcul taux
                    try:
                        taux = round((actuel / maximum) * 100, 1)
                    except:
                        taux = 0

                    print("-" * 40)
                    print(f"📍 Zone : {zone}")
                    print(f"👥 Monde actuel : {actuel} personnes")
                    print(f"📊 Capacité max : {maximum} personnes")
                    print(f"📈 Remplissage  : {taux}%")
                    print(f"🕒 Mis à jour à : {maj}")

                print("-" * 40)

            else:
                print("❌ Piscine Judaïque introuvable. Voici les piscines disponibles :")
                print(df['etablissement_etalib'].unique())
        else:
            print("❌ L'API ne renvoie aucune donnée pour le moment.")

    except Exception as e:
        print(f"❌ Erreur technique : {e}")

afficher_affluence_judaique()

"""Vérification d'un historique des affluences."""

import requests
import pandas as pd

# On interroge le catalogue des datasets
CATALOG_URL = "https://datahub.bordeaux-metropole.fr/api/records/1.0/search/"
params = {
    "dataset": "met_donnees_dispo", # Catalogue des données disponibles
    "q": "piscine",
    "rows": 20
}

def chercher_archives():
    print("🕵️ Recherche de jeux de données d'archives...")
    try:
        # On fait une recherche globale sur le portail (pas sur un dataset précis)
        # Note: L'API catalogue spécifique peut varier, on va utiliser une méthode plus simple :
        # On liste les datasets via l'API de recherche globale
        url_search = "https://datahub.bordeaux-metropole.fr/api/v2/catalog/datasets"
        params_search = {"q": "piscine", "rows": 20}

        response = requests.get(url_search, params=params_search)
        data = response.json()

        datasets_trouves = []
        if 'datasets' in data:
            for d in data['datasets']:
                info = d['dataset']
                datasets_trouves.append({
                    'ID Technique': info['dataset_id'],
                    'Titre': info['metas']['default']['title']
                })

            df = pd.DataFrame(datasets_trouves)
            pd.set_option('display.max_colwidth', None)
            display(df)
        else:
            print("Aucun dataset trouvé.")

    except Exception as e:
        print(f"Erreur lors de la recherche : {e}")

chercher_archives()

"""Comme il n'y a pas d'historique on vient créer le notre."""

import requests
import pandas as pd
import time
import os
from datetime import datetime
from google.colab import drive

# --- 1. CONFIGURATION ---
# On connecte le Google Drive pour stocker les données durablement
print("📂 Connexion à Google Drive...")
drive.mount('/content/drive')

# Le fichier sera enregistré à la racine de ton Drive
# Tu pourras le télécharger plus tard pour l'analyser
FICHIER_CSV = "/content/drive/MyDrive/historique_piscine_judaique.csv"

# L'URL du temps réel
BASE_URL = "https://datahub.bordeaux-metropole.fr/api/records/1.0/search/"
PARAMS = {
    "dataset": "bor_frequentation_piscine_tr",
    "rows": 20,
    "q": ""
}

# --- 2. FONCTION DE RÉCUPÉRATION ---
def enregistrer_donnees():
    try:
        response = requests.get(BASE_URL, params=PARAMS)
        data = response.json()

        timestamp = datetime.now()

        if data.get('nhits', 0) > 0:
            records = [r['fields'] for r in data['records']]
            df = pd.DataFrame(records)

            # On filtre uniquement sur Judaïque / Jean Boiteux
            # On convertit en string pour éviter les erreurs si la colonne est vide
            mask = df['etablissement_etalib'].astype(str).str.contains("Juda|Boiteux", case=False, na=False)
            resultat = df[mask]

            lignes_a_sauver = []

            for idx, row in resultat.iterrows():
                # On structure la donnée proprement pour le Machine Learning plus tard
                ligne = {
                    "date_heure": timestamp,
                    "jour_semaine": timestamp.strftime("%A"), # Lundi, Mardi...
                    "heure": timestamp.hour,
                    "minute": timestamp.minute,
                    "piscine": row.get('etablissement_etalib'),
                    "zone": row.get('fmizonlib'),
                    "frequentation": row.get('fmicourante'),
                    "capacite": row.get('fmizonmax'),
                    "taux_remplissage": 0 # On calculera ça juste après
                }

                # Petit calcul de sécurité
                if ligne["capacite"] and ligne["capacite"] > 0:
                    ligne["taux_remplissage"] = round(ligne["frequentation"] / ligne["capacite"] * 100, 2)

                lignes_a_sauver.append(ligne)

            # --- 3. SAUVEGARDE DANS LE CSV ---
            if lignes_a_sauver:
                df_new = pd.DataFrame(lignes_a_sauver)

                # Si le fichier existe, on ajoute à la suite (mode 'a' ppend)
                if os.path.exists(FICHIER_CSV):
                    df_new.to_csv(FICHIER_CSV, mode='a', header=False, index=False)
                    print(f"✅ {timestamp.strftime('%H:%M')} : Donnée ajoutée (Total actuel : {row.get('fmicourante')} nageurs)")
                else:
                    # Sinon on le crée (mode 'w' rite)
                    df_new.to_csv(FICHIER_CSV, mode='w', header=True, index=False)
                    print(f"🆕 {timestamp.strftime('%H:%M')} : Fichier créé avec succès !")
            else:
                print(f"⚠️ {timestamp.strftime('%H:%M')} : Piscine Judaïque non trouvée dans le flux.")

        else:
            print("❌ Erreur API : Pas de données renvoyées.")

    except Exception as e:
        print(f"❌ Erreur critique : {e}")

# --- 4. LA BOUCLE INFINIE ---
print(f"🚀 Le collecteur est lancé ! Fichier cible : {FICHIER_CSV}")
print("Ne ferme pas cet onglet tant que tu veux récolter des données.")
print("-" * 50)

try:
    while True:
        enregistrer_donnees()
        # Pause de 15 minutes (15 * 60 secondes)
        time.sleep(900)
except KeyboardInterrupt:
    print("\n🛑 Collecte arrêtée par l'utilisateur.")